### ISSUE TITLE
The link https://www.iti-tju.org/mitosisdetection/download// for the input data seems broken too.

### ISSUE THREAD

**Issue by denizff** [naivete5656/MDMLM#3]

**Comment by naivete5656** [comment]
The link was valid when I sent it.
But now it seem broken as you said.

I used the dataset that is used in CVPR 2019 Contest on Mitosis Detection in Phase Contrast images.
I attached the contest link, but the organizer seems to move website to another location (Sorry, I don't know new location.).
The organizers upload new link but the link is also broken now...

If you want to use the dataset soon, please ask the organizers of the contest.
The organizers published benckmark paper and my method use this dataset.
https://ieeexplore.ieee.org/abstract/document/9328484?casa_token=XLj19UfXiEwAAAAA:TdwkxaQwKywNwzsnDje3GgSL6960XqGUxNVLLXu2RBpWyb85DTy2f1TEqJJYYa4E9SmVjrfEzg
