### ISSUE TITLE
q

### ISSUE THREAD

**Issue by na8262** [naivete5656/MDMLM#4]
Hi! Do you process the downloaded dataset directly on MATLAB? Are there any other pre-treatments? I saw a file description in the URL where I downloaded the dataset, as if I was going to do R code processing. I would like to ask if you have to deal with it this way?
I also have a question, when I run the matlab code, the result of running it is Chinese empty, do you know why?
[document.pdf](https://github.com/naivete5656/MDMLM/files/9906450/document.pdf)

**Comment by naivete5656** [comment]
Yes, directly use MatLab code for the data. No other treatments. 
I don't know why you think R code processing is required. What is this document? I think the document is not mine, so I don't know.

The reason why you got an empty result is the input directory is wrong I think.

**Comment by naivete5656** [comment]
#5
