### ISSUE TITLE
matlab code

### ISSUE THREAD

**Issue by na8262** [naivete5656/MDMLM#5]
Excuse me. The location of my image dataset is 'E:\C2C12\dataset_01',I want to create a new folder to store the results of code runs. So I write the input path as “indir_path='E:\C2C12\dataset_01'”   and the output path as “outdir_path='E:\C2C12\processed_01'”.But the code runs incorrectly. Can you help me point out the error there? I put a screenshot of the code below. When looking for the image dataset, I did not contact the author, but I found a web link to the dataset. The link is  https://osf.io/ysaq2/. I would like to ask if when you download the image dataset, do you put all the images in one folder or put the sixteen subfolders under one total folder. Thank you very much!
[picture.pdf](https://github.com/naivete5656/MDMLM/files/9915402/picture.pdf)

**Comment by naivete5656** [comment]
> When looking for the image dataset, I did not contact the author, but I found a web link to the dataset. The link is https://osf.io/ysaq2/.

I think you can get the image from https://osf.io/ysaq2/, but the mitosis annotation is not contained. To get mitosis annotation, you should get the contact of the organizer. Did you send an e-mail to every author? 

> So I write the input path as “indir_path='E:\C2C12\dataset_01'” and the output path as “outdir_path='E:\C2C12\processed_01'”.But the code runs incorrectly. Can you help me point out the error there? I put a screenshot of the code below. 
Please show me the indir variable after running 'indir = sprintf([indir_path 'F%04d/'], fidx);'.
My code assumes the following directory structure.

c2c12
|- F0001
|   |- exp1_F0001-00001.tif
|   |    :
|   L  exp1_F0001-01013.tif
|- F0002
| :
L F0016


I think your directory structure is different from my structure.

**Comment by na8262** [comment]
> > When looking for the image dataset, I did not contact the author, but I found a web link to the dataset. The link is https://osf.io/ysaq2/.
> 
> I think you can get the image from https://osf.io/ysaq2/, but the mitosis annotation is not contained. To get mitosis annotation, you should get the contact of the organizer. Did you send an e-mail to every author?
> 
> > So I write the input path as “indir_path='E:\C2C12\dataset_01'” and the output path as “outdir_path='E:\C2C12\processed_01'”.But the code runs incorrectly. Can you help me point out the error there? I put a screenshot of the code below.
> > Please show me the indir variable after running 'indir = sprintf([indir_path 'F%04d/'], fidx);'.
> > My code assumes the following directory structure.
> 
> c2c12 |- F0001 | |- exp1_F0001-00001.tif | | : | L exp1_F0001-01013.tif |- F0002 | : L F0016
> 
> I think your directory structure is different from my structure.

Thank you very much for your reply. I sent an email to the organizer a month ago, but there was no reply.Does the entire code not run without mitotic annotation? Is it convenient for you to provide mitotic annotation？

**Comment by naivete5656** [comment]
I have annotations, but I don't have any right around the data. So it is difficult to send you the annotations.
The Matlab code can run, but the training of VNet needs annotation.
`python generate_ground_truth.py`
To run the above code, you need mitosis annotation.

**Comment by na8262** [comment]
> 我有注释，但我对数据没有任何权利。因此，很难向您发送注释。Matlab 代码可以运行，但 VNet 的训练需要注释。要运行上面的代码，您需要有丝分裂注释。`python generate_ground_truth.py`

Thank you very much for your reply and I wish you a happy life！

**Comment by naivete5656** [comment]
Sorry.

**Comment by na8262** [comment]
> Sorry.

No,don't say sorry.I should thank you for being so helpful to me.ありがとう
