### ISSUE TITLE
matlab

### ISSUE THREAD

**Issue by na8262** [naivete5656/MDMLM#6]
I also have a problem, I changed indir to indir_path and outdir to outdir_path. The matlab code can run, but the resulting folder is empty. Do you know why this is?Below is a screenshot of my problem code.Thank you so much！
[picture.pdf](https://github.com/naivete5656/MDMLM/files/9915585/picture.pdf)

**Comment by naivete5656** [comment]
Please write a question on the same thread.
#5

**Comment by naivete5656** [comment]
#
